"""corrected order_item relationships

Revision ID: 348afc5aecfd
Revises: 5c0d8f7a2b1e
Create Date: 2026-08-12 21:07:30.332300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348afc5aecfd'
down_revision = '5c0d8f7a2b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_code',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
