"""Add status, log_date, and log_time to farm_logs

Revision ID: 825c980fe2ac
Revises: 1d09bc358c05
Create Date: 2026-08-13 22:08:29.184178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825c980fe2ac'
down_revision = '1d09bc358c05'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='Completed'))
        batch_op.add_column(sa.Column('log_date', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')))
        batch_op.add_column(sa.Column('log_time', sa.String(length=10), nullable=True, server_default='08:00'))
        batch_op.alter_column('activity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('inputs_used',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_logs', schema=None) as batch_op:
        batch_op.alter_column('inputs_used',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('activity_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('log_time')
        batch_op.drop_column('log_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
