"""Add SMS logs table for SMS ordering gateway

Revision ID: 8a0dfcf21659
Revises: a9a38f136f9c
Create Date: 2026-09-21 22:21:37.031915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0dfcf21659'
down_revision = 'a9a38f136f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('related_order_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_logs_phone_number'), ['phone_number'], unique=False)

    with op.batch_alter_table('escrow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrow_events_transaction_id'))

    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrow_transactions_buyer_id'))
        batch_op.drop_index(batch_op.f('ix_escrow_transactions_farmer_id'))

    with op.batch_alter_table('group_order_commitments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_order_commitments_buyer_id'))

    with op.batch_alter_table('group_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_orders_farmer_id'))

    with op.batch_alter_table('harvest_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harvest_plans_farmer_id'))

    with op.batch_alter_table('harvest_preorders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harvest_preorders_buyer_id'))

    with op.batch_alter_table('market_price_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_price_observations_current'))
        batch_op.drop_index(batch_op.f('ix_market_price_observations_product_id'))

    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_uploaded_by_id'))

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_buyer_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_farmer_id'))

    with op.batch_alter_table('review_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_evidence_media_id'))
        batch_op.drop_index(batch_op.f('ix_review_evidence_review_id'))

    with op.batch_alter_table('sms_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_commands_phone'))

    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_requests_evidence_media_id'))
        batch_op.drop_index(batch_op.f('ix_verification_requests_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_verification_requests_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_requests_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_requests_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_requests_evidence_media_id'), ['evidence_media_id'], unique=False)

    with op.batch_alter_table('sms_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_commands_phone'), ['phone'], unique=False)

    with op.batch_alter_table('review_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_evidence_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_evidence_media_id'), ['media_id'], unique=False)

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_buyer_id'), ['buyer_id'], unique=False)

    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    with op.batch_alter_table('market_price_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_price_observations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_price_observations_current'), ['is_current'], unique=False)

    with op.batch_alter_table('harvest_preorders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harvest_preorders_buyer_id'), ['buyer_id'], unique=False)

    with op.batch_alter_table('harvest_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harvest_plans_farmer_id'), ['farmer_id'], unique=False)

    with op.batch_alter_table('group_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_orders_farmer_id'), ['farmer_id'], unique=False)

    with op.batch_alter_table('group_order_commitments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_order_commitments_buyer_id'), ['buyer_id'], unique=False)

    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrow_transactions_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrow_transactions_buyer_id'), ['buyer_id'], unique=False)

    with op.batch_alter_table('escrow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrow_events_transaction_id'), ['escrow_transaction_id'], unique=False)

    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_logs_phone_number'))

    op.drop_table('sms_logs')
    # ### end Alembic commands ###
