"""Add cooperative tables for farmer cooperative ordering

Revision ID: ec0542bcdc1a
Revises: d6ed86c626bb
Create Date: 2026-09-21 22:49:36.164679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0542bcdc1a'
down_revision = 'd6ed86c626bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooperatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('bulk_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cooperative_id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=20), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('target_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code')
    )
    with op.batch_alter_table('bulk_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_orders_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_orders_cooperative_id'), ['cooperative_id'], unique=False)

    op.create_table('bulk_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulk_order_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bulk_order_id'], ['bulk_orders.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_order_items_bulk_order_id'), ['bulk_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_order_items_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_order_items_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooperative_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_cooperative_id', 'cooperatives', ['cooperative_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_cooperative_id', type_='foreignkey')
        batch_op.drop_column('cooperative_id')

    with op.batch_alter_table('bulk_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_order_items_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_order_items_bulk_order_id'))

    op.drop_table('bulk_order_items')
    with op.batch_alter_table('bulk_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_orders_cooperative_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_orders_buyer_id'))

    op.drop_table('bulk_orders')
    op.drop_table('cooperatives')
    # ### end Alembic commands ###
