"""Make Review.farmer_id nullable for global platform reviews

Revision ID: f36070783bbb
Revises: 825c980fe2ac
Create Date: 2026-09-17 14:37:11.263169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36070783bbb'
down_revision = '825c980fe2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
